name: First Workflow
on: workflow_dispatch # when it'll be executed
jobs:
  first-job: # job name
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello!"
      - name: Multiline
        run: |
          echo "The first line"
          echo "The second line"
      - name: Print goodbye
        run: echo "Bye!"
